name: Cloud Function Deploy

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

permissions:
  contents: read

env:
  PROJECT_ID: kotlin-backend-experiments
  SERVICE: kotlin-service
  REGION: europe-central2-a

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run tests
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: test
        
  deploy:
    needs: [test]
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Build artifact
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: buildFunction
        
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: '${{ env.PROJECT_ID }}'
        credentials_json: '${{ secrets.GPG_CREDENTIALS }}'

    - id: 'deploy'
      name: 'Deploy on Google Cloud Functions'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        service: ${{ env.SERVICE }}
        region: ${{ env.REGION }}
        source: ./
        runtime: 'java11'
