name: Cloud Function Deploy

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

env:
  REGION: europe-west1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run tests
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: test

  deploy:
    needs: [ test ]

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: 'Setup JDK 11'
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: 'Setup gradle'
        uses: gradle/gradle-build-action@v3
      - name: 'Build artifact'
        run: ./gradlew build
      - run: mkdir -p ./build/deploy
      - run: cp -R ./build/libs/kotlin-template-gcloud-function-all.jar ./build/deploy

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'

      - id: 'deploy'
        name: 'Deploy on Google Cloud Functions'
        uses: google-github-actions/deploy-cloud-functions@v2
        with:
          name: App
          region: ${{ env.REGION }}
          source_dir: "./build/deploy"
          entry_point: "dev.mcatta.function.App"
          runtime: 'java11'

      - id: 'post-deploy'
        name: 'Post deploy Google Cloud Function'
        if: ${{ success() }}
        run: 'curl "${{ steps.deploy.outputs.url }}"'